import "bootstrap/dist/css/bootstrap.min.css";

// *** components **
// import { NavTop } from "../components/navbar";


export const metadata = {
  title: "book",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body className="">
        <nav style={{background: "gray", color: "#fff", padding: "15px"}}>add question</nav>
        {children}
      </body>
    </html>
  );
}
