import "bootstrap/dist/css/bootstrap.min.css";
export const metadata = {
  title: "book",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        {children}
      </body>
    </html>
  );
}
